export const T = {
  hi: {
    tagline: '|| श्रीराम जय राम जय जय राम ||',
    banner: 'राम नाम जप',
    streak: 'अनुक्रम', today: 'आज', goal: 'लक्ष्य', total: 'कुल',
    charan: 'चरण स्पर्श',
    manJap: 'मन जप', vaaniJap: 'वाणी जप',
    listening: 'श्रवण हो रहा है... "राम" बोलें',
    todayGoal: 'आज का लक्ष्य',
    malaComplete: '🎉 एक माला पूर्ण\nजय श्री राम!',
    histTitle: 'जप इतिहास', histSub: 'पिछले ९० दिन',
    best: 'सर्वोत्तम', avg: 'औसत', days: 'दिन',
    noHistory: 'अभी तक कोई इतिहास नहीं', startJap: 'जप करना शुरू करें',
    streakTitle: 'जप अनुक्रम', dayStreak: 'दिन का अनुक्रम',
    current: 'वर्तमान', longest: 'सर्वाधिक',
    goalMet: 'लक्ष्य पूरा', partial: 'आंशिक', none: 'जप नहीं',
    quote: 'राम से बड़ा राम का नाम',
    settings: 'सेटिंग', omTatSat: 'ॐ तत् सत्',
    dailyGoalSec: 'दैनिक लक्ष्य', currentGoal: 'वर्तमान लक्ष्य', apply: 'लागू करें', customGoal: 'अन्य संख्या',
    soundSec: 'ध्वनि', milestoneSounds: 'माइलस्टोन ध्वनि', haptics: 'कंपन (हैप्टिक)',
    langSec: 'भाषा',
    dataSec: 'डेटा', resetToday: 'आज की गिनती रीसेट करें', wipeAll: 'सभी डेटा मिटाएं',
    confirmWipe: 'क्या आप वाकई सभी डेटा मिटाना चाहते हैं?', cancel: 'रद्द करें', confirm: 'हाँ, मिटाएं',
    aboutSec: 'संस्करण', version: 'जय श्री राम — v2.0.0',
    vaaniOfflineNote: 'पूर्ण ऑफ़लाइन वाणी जप के लिए: फ़ोन Settings → Google → "Offline speech recognition" में हिंदी डाउनलोड करें।',
    tabs: { jap: 'जप', hist: 'इतिहास', streak: 'अनुक्रम', settings: 'सेटिंग' },
  },
  en: {
    tagline: '|| Shri Ram Jai Ram Jai Jai Ram ||',
    banner: 'Ram Naam Jap',
    streak: 'Streak', today: 'Today', goal: 'Goal', total: 'Total',
    charan: 'Charan Sparsh',
    manJap: 'Man Jap', vaaniJap: 'Vaani Jap',
    listening: 'Listening... say "Ram"',
    todayGoal: "Today's goal",
    malaComplete: '🎉 One Mala Complete\nJai Shri Ram!',
    histTitle: 'Jap History', histSub: 'Last 90 days',
    best: 'Best', avg: 'Average', days: 'Days',
    noHistory: 'No history yet', startJap: 'Start chanting',
    streakTitle: 'Jap Streak', dayStreak: 'day streak',
    current: 'Current', longest: 'Longest',
    goalMet: 'Goal met', partial: 'Partial', none: 'No jap',
    quote: 'Ram se bada Ram ka naam',
    settings: 'Settings', omTatSat: 'Om Tat Sat',
    dailyGoalSec: 'Daily Goal', currentGoal: 'Current goal', apply: 'Apply', customGoal: 'Custom number',
    soundSec: 'Sound', milestoneSounds: 'Milestone sounds', haptics: 'Haptic feedback',
    langSec: 'Language',
    dataSec: 'Data', resetToday: "Reset today's count", wipeAll: 'Erase all data',
    confirmWipe: 'Really erase ALL data?', cancel: 'Cancel', confirm: 'Yes, erase',
    aboutSec: 'Version', version: 'Jai Shri Ram — v2.0.0',
    vaaniOfflineNote: 'For fully offline Vaani Jap: download Hindi in phone Settings → Google → "Offline speech recognition".',
    tabs: { jap: 'Jap', hist: 'History', streak: 'Streak', settings: 'Settings' },
  },
};
